version: '3'

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile
  environment: &spark-common-env
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no

services:
  spark-master:
    <<: *spark-common
    user: "1001"
    environment:
      <<: *spark-common-env
      SPARK_MODE: master
    ports:
      - 8090:8080
      - 7077:7077

  spark-worker:
    <<: *spark-common
    user: "1001"
    environment:
      <<: *spark-common-env
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    depends_on:
      - spark-master
